name: CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          mvn spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_HUB_USERNAME }}/ipfs-resizer:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/ipfs-resizer:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/ipfs-resizer:latest
      - name: docker login
        run: | # log into docker hub account
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Push
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ipfs-resizer:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ipfs-resizer:latest
